### ISSUE TITLE
Can we share some pre-trained weights?

### ISSUE THREAD

**Issue by CrazySherman** [kevinhughes27/TensorKart#57]
Amazing project I can't appreciate more of the fun it brought me, it'd be great if you can share some pre-trained weights

**Comment by kevinhughes27** [comment]
I've resisted sharing data / models since I wanted to focus on the process instead. However I've got a lot of requests and the samples could be used to bootstrap a better AI etc so here they are:

https://www.dropbox.com/sh/inq8y94nxg7zq8p/AABoT2MaYsJUz11MZDXtzTIka?dl=0

Its just the samples since I don't know if my trained weights are correct after the recent changes to the code.

**Comment by kevinhughes27** [comment]
It might take a bit for the upload to finish since I was ignoring this folder in Dropbox. Also the link changed from the first reply.
