### ISSUE TITLE
Assertion error running play.py

### ISSUE THREAD

**Issue by ne0hit** [kevinhughes27/TensorKart#59]
Hello Kevin, I ran into your project when I was digging about Tensorflow so I decided to give it a try and see how it works. After some changes (bold text) suggested in previous comments. I was able to record, prepare samples and finally try to play the trained agent but now I am getting an error so maybe you might know whats happening. Here the changes that I have added to my environment some screenshots and a video.

If i dont use EmptyImage and EmptyBitmap wx does not work.
record.py
  # Images
        img = wx.**EmptyImage**(320,240)
        self.image_widget = wx.StaticBitmap(self.img_panel, wx.ID_ANY, wx.**EmptyBitmap**(320,240))
        bmp = wx.**EmptyBitmap**(Screenshot.SRC_W, Screenshot.SRC_H)

I had to disable XVFB from the config file otherwise I am not seeing anything on my desktop, for some reason it is not working for me.
config.yml (gym_mupen64plus)
# XVFB config:
USE_XVFB: **false**
XVFB_CMD: Xvfb
TMP_DIR: /dev/shm
VGLRUN_CMD: vglrun

Finally when I run the play.py I am getting an assertion error. 

![screenshot from 2018-03-19 15-13-38](https://user-images.githubusercontent.com/37481118/37602500-bf7476e0-2b8c-11e8-9dbb-9c51a1cd2f82.png)

I am not sure the record is working as expected because I am seeing some strange values. Is this the expected output of record.py?

![screenshot from 2018-03-19 14-25-26](https://user-images.githubusercontent.com/37481118/37602562-e3292270-2b8c-11e8-99e3-6640d56e8dd4.png)
![screenshot from 2018-03-19 14-26-25](https://user-images.githubusercontent.com/37481118/37602563-e381ac56-2b8c-11e8-99d6-d4eaffac9d13.png)

Here a video when the issue happens. Just before the race starts.

[AssertionError nvec.mp4.zip](https://github.com/kevinhughes27/TensorKart/files/1825436/AssertionError.nvec.mp4.zip)

Hope you could help and give some advise.

Best Regards!

Oscar

**Comment by bzier** [comment]
Related issue [here](https://github.com/bzier/gym-mupen64plus/issues/40)

**Comment by bzier** [comment]
Discussion about details regarding `XVFB` and the problem/workaround for the 'assertion error' being encountered is in the related [issue](https://github.com/bzier/gym-mupen64plus/issues/40) in the `gym-mupen64plus` repo.
 
@ne0hit, 
However, there are a couple things specific to the TensorKart project which I think are better discussed here:

What version of `wxPython` are you using? You mentioned needing to make some changes to get the `record.py` to work properly, but we haven't ever bumped into that before. You said if you don't use the EmptyImage and EmptyBitmap, it "does not work". Can you describe that a little more? Are there any specific errors you encounter?

As far as the resulting output from `record.py`, I have to say that it has been quite some time since I ran that process and I don't recall what it 'should' look like. Kevin is currently away from the project, so I'm not sure if he'll have the chance to chime in here. Hopefully with resolution on the other issue, the question may answer itself. If not, we'll see what else we can figure out.

**Comment by ne0hit** [comment]
Brian, I am using python-wxgtk3.0 and the issue that I was having is pretty much the same issue previously reported by a couple of users in this thread discussion: https://github.com/kevinhughes27/TensorKart/issues/11 "simama" was able to solve the issue using the EmptyImage and EmptyBitmap APIS so I followed his suggestion, @kevinhughes27 said he was using 3.0.3 so maybe I need to install such version manually what do you think?. I will try the changes in the gym module and then I will write back here regarding the record.py output.

**Comment by bzier** [comment]
Ah ok, I had forgotten about that other issue (#11). The current version of wxPython is now `4.0.1` which is very different than the previous version `3.x.x`. I think TensorKart was updated to use version `4.x.x`, but to be honest, wx has been a huge pain all along. Kevin would ultimately like to remove it, but it is being used for the GUI at the moment. We've discussed eliminating it, but haven't done so yet. If you got it working and the screenshots are showing properly, I wouldn't worry too much about it.

**Comment by bzier** [comment]
@ne0hit Heads-up... I finally actually removed the dependency on `wxPython`. I re-wrote the `record.py` application not to use it for the GUI or the screenshots. Details are in #60. @kevinhughes27 merged the PR a few hours ago. No pressure to fetch the latest, but didn't want you to be surprised if/when you pull the changes.

**Comment by ne0hit** [comment]
@bzier  Thanks for the heads-up.

**Comment by bzier** [comment]
@ne0hit Since we got you past the assertion error in the other repository ([here](https://github.com/bzier/gym-mupen64plus/issues/40)) and it sounds like everything is up-and-running, can we go ahead and close this issue?

**Comment by bzier** [comment]
The original issue was resolved in the other repository [here](https://github.com/bzier/gym-mupen64plus/issues/40), `wxPython` was removed as a dependency and should no longer be an issue, and haven't heard anything else on this for over a month. I'm going to close this. Feel free to re-open if necessary.
