### ISSUE TITLE
Model Trained: Straight Line

### ISSUE THREAD

**Issue by ne0hit** [kevinhughes27/TensorKart#61]
Hello,

I was trying run the trained model and I thought that maybe the player was going in straight line due to lack of training nevertheless after generating the model with samples for around 6 races the behavior is still the same, any ideas about what the issue might be? For example the easiest track is Luigis racetrack and as soon as the player gets to the first curve the model is not reacting as expeted I think. I am not seeing the values between -80 and 80. Is worth to mention that I did double check the Joystick samples and those are ok going from -1 to 1 according to the record.py file.

Best Regards!

**Comment by bzier** [comment]
The recording of the samples is between [-1, 1] as you see. That is handled during `play` by scaling by 80. See [here](https://github.com/kevinhughes27/TensorKart/blob/a64999e0b81ce9e2e54594b55d9a355cad11a1a7/play.py#L43).

When you are running `play.py` the console should be printing the controller output. What kinds of values are you seeing? Can you show a screenshot?

Another thing worth pointing out is that the training process can end up 'ignoring' the steering values because it can be pretty jittery. See #49 and this discussion starting [here-ish](https://github.com/bzier/gym-mupen64plus/issues/19#issuecomment-323548045). In both discussions, Kevin mentions the problem with aliasing with respect to turns. He also explains it a bit in his blog [here](https://kevinhughes.ca/blog/tensor-kart) in the section "Playing Revisited", specifically point 2. My guess is that you may be encountering the same thing.

**Comment by ne0hit** [comment]
Thanks for the info Brian, I think that you can close the ticket, I guess my driving was not sufficiently smooth to properly train the model. Now its working. Thanks.
